### ISSUE TITLE
Review #2

### ISSUE THREAD

**Issue by LidiaIvanova** [amr9855/exhangeDataBetweenActivities#2]
Your code has become easier))

1. You added scrollview for landscape orientation, but, I think, to scroll content is not useful.
Let's try  to add other layout for landscape with other positions of answer variants.

2. UIElements identifier like "_1" is bad, because it's very difficult to determine the type and goal of element by this name. Try something like "firstRadioButton".

3. `  Toast.makeText(this, "click the time for a hint", Toast.LENGTH_SHORT).show();`
In Android development we always put strings into special file strings.xml. Please, replace all your strings.

4. Imports like import static com.example.myapplication.Utility.prepareLayout
and using this method like prepareLayout(R.drawable.saad, SAAD) is hard to read and understand (because I should remember that this method is method of Utility. But what if you use a lot of classes?).
Change it to Utility.prepareLayout(...)

5. ` public static void exit(Context context) {
        Intent intent = new Intent(Intent.ACTION_MAIN);
        intent.addCategory(Intent.CATEGORY_HOME);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startActivity(intent);
    }`
It's hard way to close activity. Try just activity.finish()

You are very close to final) Don't forget replace string literals to strings.xml

**Comment by AmrAbuelhamd** [comment]
about the fifth point, i am using the exit function to exist the whole app not only the current activity for that using finish activity will not do the task for me unfortunately

**Comment by AmrAbuelhamd** [comment]
i have fixed all the others
